#!/bin/bash

# A script to print all the keybindings in the i3 config file with pretty minimal formatting

egrep "^bindsym.*" ~/.config/i3/config | \
	awk '{printf "%-25s", $2; $1 = ""; $2 = ""; printf "%s\n", $0}' | \
	sort | \
	less
